policies:
  - name: p1
    data.yaml: |
      a: 1
      b: 2
    source: |
      # METADATA
      # entrypoint: true
      package example.allow
      import future.keywords.if

      # METADATA
      # description: This policy never denies
      deny if {
        false
      }

  - name: p2
    source: |
      # METADATA
      # entrypoint: true
      package example.deny
      import future.keywords.if

      # METADATA
      # description: This policy always denies
      deny[format(rego.metadata.rule())] {
        true
      }

      format(meta) := {"reason": meta.description}

  - name: p3
    source: |
      # METADATA
      # entrypoint: true
      package example.path
      import future.keywords.if

      # METADATA
      # description: Path is not allowed
      deny[format(rego.metadata.rule())] {
        not startswith(input.path, "/path/allow")
      }

      format(meta) := {"reason": meta.description}
