name: CI

on:
  push:
    branches: [ main, develop ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '**.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Restore Tools
      run: dotnet tool restore
    - name: Calc Version
      run: dotnet gitversion /updateprojectfiles /output buildserver
    - name: Build
      run: dotnet build -c Release
    - name: Download OPA CLI
      run: |
        echo "Downloading OPA ${OPA_CLI_VERSION}"
        curl -L --fail -o /usr/local/bin/opa https://openpolicyagent.org/downloads/${OPA_CLI_VERSION}/opa_linux_amd64_static
        chmod 755 /usr/local/bin/opa
      env:
        OPA_CLI_VERSION: ${{ vars.OPA_CLI_VERSION }}
    - name: Test
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov
    - name: Coveralls
      uses: coverallsapp/github-action@v2
      with:
        file: ./tests/TestResults/coverage.info
        format: lcov
