name: Publish

on:
  workflow_dispatch:
    branches: [ main, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Restore Tools
      run: dotnet tool restore
    - name: Calc Version
      run: dotnet gitversion /updateprojectfiles /output buildserver
    - name: Pack
      run: dotnet pack -c Release -o ./artifacts
    - name: Push Nuget Package
      run: dotnet nuget push "./artifacts/*.nupkg" -k ${NUGET_API_KEY} -s https://api.nuget.org/v3/index.json --skip-duplicate
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
    - name: Push Nuget Symbols
      run: dotnet nuget push "./artifacts/*.snupkg" -k ${NUGET_API_KEY} -s https://api.nuget.org/v3/index.json --skip-duplicate
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
